accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    # path('', views.temp, name='temp'),
    path('profile/<username>/', views.profile, name='profile'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('cart/<int:cloth_pk>/', views.add_cart, name='add_cart'),
    path('purchase/<int:cloth_pk>/', views.purchase, name='purchase'),
    
    # 아래 두 경로는 위 경로와 달리 cloth_pk가 아닌 cart_pk, purchase_pk임에 주의!!
    path('<username>/cart/<int:cart_pk>/delete/', views.delete_cart_item, name='delete_cart_item'),
    path('<username>/purchase/<int:purchase_pk>/delete/', views.delete_purchase_log, name='delete_purchase_log'),
]

clothes/urls.py
from django.urls import path
from . import views


app_name = 'clothes'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:cloth_pk>/', views.detail, name='detail'),
    path('<int:cloth_pk>/delete/', views.delete, name='delete'),
    path('<int:cloth_pk>/update/', views.update, name='update'),
    path('search/', views.search, name='search'),
    # path('tags/<int:tag_pk>/', views.tagged_clothes, name='tagged_clothes'),
    path('<int:cloth_pk>/likes/', views.likes, name='likes'),
    path('category/<str:subject>/', views.category, name='category'),
    path('recommends/create/', views.recommend_create, name='recommend_create'),
    path('recommends/<int:recommend_pk>/', views.recommend_detail, name='recommend_detail'),
    path('recommends/<int:recommend_pk>/delete/', views.recommend_delete, name='recommend_delete'),
    path('recommends/<int:recommend_pk>/update/', views.recommend_update, name='recommend_update'),
    path('recommends/<int:recommend_pk>/comments/', views.comments_create, name='comments_create'),
    path('recommends/<int:recommend_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('shop/', views.shop, name='shop'),
    path('md-pick/', views.md_pick, name='md_pick'),
    path('gender/<str:gender>/', views.gender, name='gender'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('clothes/', include('clothes.urls')),
    path('reviews/', include('reviews.urls')),
    path('accounts/', include('allauth.urls')),
    # localhost:8000을 localhost:8000/clothes로 redirect
    path('', (lambda request: redirect('clothes:index'))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views


app_name = 'reviews'
urlpatterns = [
    path('cloth/<int:cloth_pk>/review/create/', views.review_create, name='review_create'), 
    path('cloth/<int:cloth_pk>/review/<int:review_pk>/update/', views.review_update, name='review_update'),
    path('cloth/<int:cloth_pk>/review/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
]

clothes/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from taggit.managers import TaggableManager
from django.utils import timezone
from datetime import timedelta,datetime
import os

# Create your models here.

class Cloth(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_clothes')
    brand = models.CharField(max_length=30)
    name = models.CharField(max_length=50)
    price = models.DecimalField(blank=True, max_digits=10, decimal_places=0)
    hits = models.PositiveIntegerField(default=0)

    def clothes_image_path(instance, filename):
        return f'clothes/{instance.name}/{filename}'

    thumbnail = ProcessedImageField(upload_to=clothes_image_path, 
                                    blank=True, processors=[ResizeToFill(400,400)],
                                    format='JPEG',
                                    options={'quality': 100})
    

    gender_choices = (('Male', '남'), ('Female', '여'), ('Unisex', '공용'),)
    gender = models.CharField(max_length=10, choices=gender_choices)
    
    category_choices = (('outer', '아우터'), ('top', '상의'), ('bottom', '하의'), ('cap', '모자'), ('accessories', '악세서리'))
    category = models.CharField(max_length=20, choices=category_choices)

    size_choices = (('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Free', 'free'))
    size = models.CharField(max_length=15, choices=size_choices, default='free')

    tags = TaggableManager(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    

class ClothImage(models.Model):
    cloth = models.ForeignKey(to=Cloth, on_delete=models.CASCADE)
    
    def clothes_image_path(instance, filename):
        return f'clothes/{instance.cloth.name}/{filename}'
    
    image = ProcessedImageField(upload_to=clothes_image_path, blank=True,
                                processors=[ResizeToFill(250,300)],
                                format='JPEG',
                                options={'quality': 100})


class Recommend(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    clothes = models.ManyToManyField(Cloth, related_name='recommendations')
    title = models.CharField(max_length=30)
    content = models.CharField(max_length=200)
    hits = models.PositiveIntegerField(default=0)
    tags = TaggableManager(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    

    @property
    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False
        

class RecommendImage(models.Model):
    recommend = models.ForeignKey(Recommend, on_delete=models.CASCADE)
    image = ProcessedImageField(upload_to='', blank=True,
                                processors=[ResizeToFill(700,900)],
                                format='JPEG',
                                options={'quality': 100})


class Comment(models.Model):
    recommend = models.ForeignKey(Recommend, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False
    


class ClothDescriptionImage(models.Model):
    cloth = models.ForeignKey(to=Cloth, on_delete=models.CASCADE)
    
    def clothes_image_path(instance, filename):
        return f'clothes/{instance.cloth.name}/{filename}'
    
    description_image = ProcessedImageField(upload_to=clothes_image_path, blank=True,
                                processors=[],
                                format='JPEG',
                                options={'quality': 100})

reviews/models.py
from django.db import models
from django.conf import settings
from clothes.models import Cloth
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import os

# Create your models here.

class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    clothes = models.ForeignKey(Cloth, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    content = models.CharField(max_length=500)
    rating = models.IntegerField()
    
    def star_rating(self):
        return '⭐' * self.rating
    
    def empty_star_rating(self):
        return '☆' * (5 - self.rating)

    created_at = models.DateTimeField(auto_now_add=True)


class ReviewImage(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    image = ProcessedImageField(upload_to='', blank=True,
                                processors=[ResizeToFill(100,100)],
                                format='JPEG',
                                options={'quality': 80})

clothes/forms.py
from django import forms
from .models import Cloth, ClothImage, Recommend, RecommendImage, Comment, ClothDescriptionImage
from taggit.managers import TaggableManager
from taggit.forms import TagField, TagWidget

class ClothForm(forms.ModelForm):
    brand = forms.CharField(label='브랜드', widget=forms.TextInput(attrs={'class': 'form-control',}))
    name = forms.CharField(label='상품명', widget=forms.TextInput(attrs={'class': 'form-control',}))
    gender = forms.ChoiceField(label='성별', choices=Cloth.gender_choices, widget=forms.Select(attrs={'class': 'form-select',}))
    # category = forms.ChoiceField(label='분류', widget=forms.Select(attrs={'class': 'form-select',}))
    category = forms.ChoiceField(label='분류', choices=Cloth.category_choices, widget=forms.Select(attrs={'class': 'form-select'}),)
    size = forms.ChoiceField(label='사이즈', choices=Cloth.size_choices, widget=forms.Select(attrs={'class': 'form-select',}))
    price = forms.IntegerField(label='가격', widget=forms.NumberInput(attrs={'class': 'form-control',}))
    tags = forms.CharField(label='태그', widget=TagWidget(attrs={'class': 'form-control',}))
    thumbnail = forms.ImageField(label='썸네일 이미지', widget=forms.ClearableFileInput(attrs={'class': 'form-control'})),

    class Meta:
        model = Cloth
        fields = ('brand', 'name', 'gender', 'category', 'size', 'price', 'tags', 'thumbnail',)


class ClothImageForm(forms.ModelForm):
    image = forms.ImageField(label='상품 이미지 업로드', widget=forms.ClearableFileInput(attrs={'class': 'form-control', 'multiple': True,},), required=False,)

    class Meta:
        model = ClothImage
        fields = ('image', )


class RecommendForm(forms.ModelForm):
    title = forms.CharField(label='코디명', widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 700px'}),)
    content = forms.CharField(label='내용',widget=forms.Textarea(attrs={'class': 'form-control', 'style': 'width: 700px; height: 200px'}),)
    tags = forms.CharField(label='코디 태그',widget=TagWidget(attrs={'class': 'form-control', 'style': 'width: 700px'}),)
    clothes = forms.ModelMultipleChoiceField(queryset=Cloth.objects.all(),label='상품 정보',widget=forms.CheckboxSelectMultiple(),)

    class Meta:
        model = Recommend
        fields = ('title', 'content', 'tags', 'clothes',)


class RecommendImageForm(forms.ModelForm):
    image = forms.ImageField(label='스타일 이미지 업로드', widget=forms.ClearableFileInput(attrs={'class': 'form-control', 'multiple': True,},), required=False,)
    
    class Meta:
        model = RecommendImage
        fields = ('image',)


class ClothDescriptionImageForm(forms.ModelForm):
    description_image = forms.ImageField(label='상품 설명 이미지 업로드', widget=forms.ClearableFileInput(attrs={'class': 'form-control', 'multiple': True,},), required=False,)

    class Meta:
        model = ClothDescriptionImage
        fields = ('description_image', )
        

class CommentForm(forms.ModelForm):
    content = forms.CharField(label='댓글', widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Comment
        fields = ('content',)

clothes/templates/clothes/detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}


{% block head %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
{% endblock head %}


{% block content %}
<div class="container">

  {% if request.user.is_superuser %}
    <div class="d-flex justify-content-end">
      <form action="{% url 'clothes:delete' cloth.pk %}" method="post" class="ms-3">
        {% csrf_token %}
        <a href="{% url 'clothes:update' cloth.pk %}" class="" style="width: 1rem;">
          {% comment %} <i class="bi bi-pencil-square text-dark"></i> {% endcomment %}
          <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-pencil-square text-primary" viewBox="0 0 16 16">
            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
          </svg>
        </a>
        <button type="submit" class="border-0 bg-transparent p-1" style="width: 1rem;">
          {% comment %} <i class="bi bi-trash3 text-danger"></i> {% endcomment %}
          <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-trash3 text-danger" viewBox="0 0 16 16">
            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
          </svg>
        </button>
      </form>
    </div>
  {% endif %}

  <div class="row d-flex justify-content-around overflow-x-scroll" style="min-width: 750px;">
    <div class="col-6 col-sm-6 col-md-5 text-center overflow-hidden p-0">
      
      {% if cloth.thumbnail %}
      <img src="{{ cloth.thumbnail.url }}" style="object-fit:cover;" class="mb-3" width="100%" alt="">
      {% else %}
      <img src="{% static 'img/common/passionon.png' %}" style="object-fit:cover;" class="mb-3" width="100%" alt="">
      {% endif %}

      {% for cloth_image in cloth_images %}
      <div class="thumbnail-container">
        <img src="{{ cloth_image.image.url }}" alt="Clothes Image" class="thumbnail" 
        data-large-image="{{ cloth_image.image.url }}"
        {% if cloth.thumbnail %}
        data-thumbnail-image="{{ cloth.thumbnail.url }}">
        {% else %}
        data-thumbnail-image="{% static 'img/common/passionon.png' %}">
        {% endif %}
      </div>
      {% endfor %}
      
    </div>

    <div class="col-4 col-sm-4 col-md-4">

      <p class="text-secondary">{{ cloth.brand }}</p>
      <p class="fw-bold">{{ cloth.name }}</p>
      <p {% if cloth.category == 'accessories' %}hidden{% endif %}>size : <span id="clothSize">{{ cloth.size }}</span></p>
      <p><span id="clothesPrice">{{ cloth.price|intcomma }}</span>원</p>
      {% comment %} <div class="dropdown">
        <button class="btn btn-outline-primary dropdown-toggle mb-4" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          옵션을 선택하세요
        </button>
        <ul class="dropdown-menu">
          <li class="dropdown-item" style="cursor: pointer">Small</li>
          <li class="dropdown-item" style="cursor: pointer">Medium</li>
          <li class="dropdown-item" style="cursor: pointer">Large</li>
          <li class="dropdown-item" style="cursor: pointer">Free</li>              
        </ul>
      </div> {% endcomment %}
      <button class="btn btn-outline-primary btn-sm me-2" onclick="decrease()">-</button>
      <input class="me-2" type="number" id="numInput" value="1" min="1" oninput="checkValue(); updateTotal();" style="width: 50px;">
      <button class="btn btn-outline-primary btn-sm" onclick="increase()">+</button>
      <p id="totalAmount" class="mt-3"></p>

      <div>
        <b>Tag</b>
        <div class="mt-2 mb-4">
          {% for tag in tags %}
            <button type="button" class="btn btn-outline-dark btn-sm">{{ tag }}</button>
          {% endfor %}             
        </div>      
      </div>

      <p class="text-danger">전 상품 무료배송</p>
      <div class="d-flex flex-column justify-content-center">
        <form action="{% url 'accounts:purchase' cloth.pk %}" method="post" class="">
          {% csrf_token %}
          <input type="hidden" name="quantity" value="1" id="purchaseQuantityInput">
          {% comment %} <input type="hidden" name="size" value="free"> {% endcomment %}
          <button class="btn btn-dark btn-lg align-content-center mb-2 w-100">
            바로구매
          </button>
        </form>

        <div class="d-flex justify-content-evenly mb-2">
          {% if request.user.is_authenticated %}
          <form id="likes-form" data-cloth-id="{{ cloth.pk }}" class="index--heart flex-grow-1">
            {% csrf_token %}
              {% if request.user in cloth.like_users.all %}
              <button class="btn btn-outline-dark btn-lg align-content-center w-100" type="submit">
                <i class="bi bi-suit-heart-fill" id="cloth-heart"></i>
              </button>
              {% else %}
              <button class="btn btn-outline-dark btn-lg align-content-center w-100" type="submit">
                <i class="bi bi-suit-heart" id="cloth-heart"></i>
              </button>
              {% endif %}
          </form>
          {% else %}
          <div class="index--heart flex-grow-1">
            <button class="btn btn-outline-dark btn-lg align-content-center w-100" type="submit">
              <i class="bi bi-suit-heart" id="cloth-heart"></i>
            </button>
          </div>
          {% endif %}

          <form action="{% url 'accounts:add_cart' cloth.pk %}" method="post" class="flex-grow-1">
            {% csrf_token %}
            <input type="hidden" name="quantity" value="1" id="quantityInput">
            {% comment %} <input type="hidden" name="size" value="free"> {% endcomment %}
            <button class="btn btn-outline-dark btn-lg align-content-center w-100">            
              <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
              </svg>
            </button>
          </form>
        </div>

      </div>

    </div>
    </div>

  </div>
</div>

  <div class="mt-3 d-flex justify-content-center">
    <div class="col-9 col-sm-9 col-md-9">
      <ul class="nav nav-tabs mt-4">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">상세정보</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" href="#review">후기</a>
        </li>
        {% comment %} <li class="nav-item">
          <a class="nav-link" href="#">상품문의</a>
        </li> {% endcomment %}
      </ul>

      <div class="text-center my-5">
        {% for img in cloth_description_images %}
        <img src="{{ img.description_image.url }}" alt="" class="d-block mx-auto" style="max-width: 50rem;">
        {% empty %}
        <p class="text-secondary text-center">
          상품 정보가 없습니다.
        </p>
        {% endfor %}
        {% comment %} <img src="https://image.musinsa.com/images/prd_img/2021081812070300000022384.jpg" alt=""> {% endcomment %}
      </div>
      <div class="my-5 d-flex justify-content-center">
        <a href="#" class="btn btn-dark" style="width: 10rem;">top</a>
      </div>


      <div id='review'></div>
      <div class="border-bottom border-dark">
        <div class="fs-4 my-1 ms-3 d-flex justify-content-between">
          <div>
            <b>구매후기 ({{ cloth.review_set.count }}개)</b>
            <span class="fs-5">리뷰 평점 : {{ review_avg|floatformat:1 }}</span>
          </div>
          {% if request.user.is_authenticated and exist_flag %}
          <div><a href="{% url 'reviews:review_create' cloth.pk %}" class="btn btn-dark">리뷰 작성</a></div>
          {% endif %}
        </div>
      </div>

      {% for review in reviews %}
      <div class="d-flex col-12 mt-3 mx-auto">
        <div class="flex-column col-3 text-center">
          <div class="mx-auto my-2 image_container">
            {% if review.reviewimage_set.all.first %}
              <img src="{{ review.reviewimage_set.all.first.image.url }}" alt="" width="100%">      
            {% else %}
              <img src="{% static 'img/common/passionon.png' %} " alt="" width="100%">                
            {% endif %}              
          </div>
          {% comment %} <p class="small text-secondary">옵션: 30</p> {% endcomment %}
        </div>
        
        <div class="flex-column col-9">
          <div class="me-3 d-flex justify-content-end">
            <div class="d-flex">
              {# 본인 리뷰 수정/삭제 #}
              {% if request.user == review.user %}
              <form action="{% url 'reviews:review_delete' cloth.pk review.pk %}" method="post" class="ms-3">
                {% csrf_token %}
                <a href="{% url 'reviews:review_update' cloth.pk review.pk %}" class="" style="width: 1rem;">
                  {% comment %} <i class="bi bi-pencil-square text-dark"></i> {% endcomment %}
                  <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-pencil-square text-primary" viewBox="0 0 16 16">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                  </svg>
                </a>
                <button type="submit" class="border-0 bg-transparent p-1" style="width: 1rem;">
                  {% comment %} <i class="bi bi-trash3 text-danger"></i> {% endcomment %}
                  <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-trash3 text-danger" viewBox="0 0 16 16">
                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                  </svg>
                </button>
              </form>
                {% endif %}
              </div>

          </div>
          <div class="d-flex">
            <p><b>{{ review.user }}</b></p>
            <p class="ms-2">{{ review.star_rating }}</p>
            
          </div>
          <div>{{ review.content }}</div>
          
        </div>
      </div>

      {% if not forloop.last %}
      <hr>
      {% else %}
      <hr class="border-0 py-5">
      {% endif %}
      
      {% empty %}
      <hr class="border-0 py-5">
      {% endfor %}

      {% comment %} <div class="mt-5" id='QNA'></div>
        <div class="border border-dark border-start-0 border-end-0 d-flex justify-content-start">
          <div class="fs-4 my-1 ms-3"><b>상품문의</b></div>              
        </div>
        <div class="d-flex text-center">
          <p class="col">번호</p>
          <p class="col">답변여부</p>
          <p class="col-5">내용</p>
          <p class="col">작성자</p>
          <p class="col">작성일자</p>
        </div> {% endcomment %}

    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="{% static 'javascript/detail.js' %}"></script>
{% endblock content %}