accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    # path('', views.temp, name='temp'),
    path('profile/<username>/', views.profile, name='profile'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('cart/<int:cloth_pk>/', views.add_cart, name='add_cart'),
    path('purchase/<int:cloth_pk>/', views.purchase, name='purchase'),
    
    # 아래 두 경로는 위 경로와 달리 cloth_pk가 아닌 cart_pk, purchase_pk임에 주의!!
    path('<username>/cart/<int:cart_pk>/delete/', views.delete_cart_item, name='delete_cart_item'),
    path('<username>/purchase/<int:purchase_pk>/delete/', views.delete_purchase_log, name='delete_purchase_log'),
]

clothes/urls.py
from django.urls import path
from . import views


app_name = 'clothes'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:cloth_pk>/', views.detail, name='detail'),
    path('<int:cloth_pk>/delete/', views.delete, name='delete'),
    path('<int:cloth_pk>/update/', views.update, name='update'),
    path('search/', views.search, name='search'),
    # path('tags/<int:tag_pk>/', views.tagged_clothes, name='tagged_clothes'),
    path('<int:cloth_pk>/likes/', views.likes, name='likes'),
    path('category/<str:subject>/', views.category, name='category'),
    path('recommends/create/', views.recommend_create, name='recommend_create'),
    path('recommends/<int:recommend_pk>/', views.recommend_detail, name='recommend_detail'),
    path('recommends/<int:recommend_pk>/delete/', views.recommend_delete, name='recommend_delete'),
    path('recommends/<int:recommend_pk>/update/', views.recommend_update, name='recommend_update'),
    path('recommends/<int:recommend_pk>/comments/', views.comments_create, name='comments_create'),
    path('recommends/<int:recommend_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('shop/', views.shop, name='shop'),
    path('md-pick/', views.md_pick, name='md_pick'),
    path('gender/<str:gender>/', views.gender, name='gender'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('clothes/', include('clothes.urls')),
    path('reviews/', include('reviews.urls')),
    path('accounts/', include('allauth.urls')),
    # localhost:8000을 localhost:8000/clothes로 redirect
    path('', (lambda request: redirect('clothes:index'))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clothes/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from taggit.managers import TaggableManager
from django.utils import timezone
from datetime import timedelta,datetime
import os

# Create your models here.

class Cloth(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_clothes')
    brand = models.CharField(max_length=30)
    name = models.CharField(max_length=50)
    price = models.DecimalField(blank=True, max_digits=10, decimal_places=0)
    hits = models.PositiveIntegerField(default=0)

    def clothes_image_path(instance, filename):
        return f'clothes/{instance.name}/{filename}'

    thumbnail = ProcessedImageField(upload_to=clothes_image_path, 
                                    blank=True, processors=[ResizeToFill(400,400)],
                                    format='JPEG',
                                    options={'quality': 100})
    

    gender_choices = (('Male', '남'), ('Female', '여'), ('Unisex', '공용'),)
    gender = models.CharField(max_length=10, choices=gender_choices)
    
    category_choices = (('outer', '아우터'), ('top', '상의'), ('bottom', '하의'), ('cap', '모자'), ('accessories', '악세서리'))
    category = models.CharField(max_length=20, choices=category_choices)

    size_choices = (('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Free', 'free'))
    size = models.CharField(max_length=15, choices=size_choices, default='free')

    tags = TaggableManager(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    

class ClothImage(models.Model):
    cloth = models.ForeignKey(to=Cloth, on_delete=models.CASCADE)
    
    def clothes_image_path(instance, filename):
        return f'clothes/{instance.cloth.name}/{filename}'
    
    image = ProcessedImageField(upload_to=clothes_image_path, blank=True,
                                processors=[ResizeToFill(250,300)],
                                format='JPEG',
                                options={'quality': 100})


class Recommend(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    clothes = models.ManyToManyField(Cloth, related_name='recommendations')
    title = models.CharField(max_length=30)
    content = models.CharField(max_length=200)
    hits = models.PositiveIntegerField(default=0)
    tags = TaggableManager(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    

    @property
    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False
        

class RecommendImage(models.Model):
    recommend = models.ForeignKey(Recommend, on_delete=models.CASCADE)
    image = ProcessedImageField(upload_to='', blank=True,
                                processors=[ResizeToFill(700,900)],
                                format='JPEG',
                                options={'quality': 100})


class Comment(models.Model):
    recommend = models.ForeignKey(Recommend, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False
    


class ClothDescriptionImage(models.Model):
    cloth = models.ForeignKey(to=Cloth, on_delete=models.CASCADE)
    
    def clothes_image_path(instance, filename):
        return f'clothes/{instance.cloth.name}/{filename}'
    
    description_image = ProcessedImageField(upload_to=clothes_image_path, blank=True,
                                processors=[],
                                format='JPEG',
                                options={'quality': 100})

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm, PasswordChangeForm
from .models import Cart, PurchaseLog


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        label = '아이디',
        widget = forms.TextInput(
            attrs = {}
        )
    )
    password = forms.CharField(
        label = '비밀번호',
        widget = forms.PasswordInput(
            attrs = {}
        )
    )


class CustomUserCreationForm(UserCreationForm):
    password1 = forms.CharField(
        label='비밀번호*', 
        widget=forms.PasswordInput(attrs={'placeholder' : '영문과 숫자를 조합해주세요'}),
        # help_text=password_validation.password_validators_help_text_html(),
        help_text=None,
        )
    password2 = forms.CharField(
        label='비밀번호 확인*', 
        widget=forms.PasswordInput(attrs={'placeholder' : '비밀번호를 확인해주세요'}),
        )
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'password1', 'password2',)
        labels = {
            'username': '아이디*',
        }
        widgets = {
            'username': forms.TextInput(attrs={'placeholder' : '아이디를 입력해주세요'}),
        }
        help_texts = {
            'username': None,
        }
        
        
        
class CustomUserChangeForm(UserChangeForm):
    password = None
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('last_name', 'first_name', 'email', 'profile_image',)
        labels = {
            'first_name': '이름*',
            'last_name': '성*',
            'email': '이메일*',
            'profile_image': '프로필 이미지*',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={}),
            'last_name': forms.TextInput(attrs={}),
            'email': forms.TextInput(attrs={}),
            'profile_image': forms.ClearableFileInput(attrs={})
        }
        
        
class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='현재 비밀번호*', 
        widget=forms.PasswordInput(attrs={}),
        )
    new_password1 = forms.CharField(
        label='새로운 비밀번호*', 
        widget=forms.PasswordInput(attrs={}),
        # help_text=password_validation.password_validators_help_text_html(),
        help_text = None,
        )
    new_password2 = forms.CharField(
        label='새로운 비밀번호 확인*', 
        widget=forms.PasswordInput(attrs={}),
        )
    
    class Meta:
        model = get_user_model()
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login, logout as auth_logout, update_session_auth_hash
from .forms import CustomAuthenticationForm, CustomUserCreationForm, CustomUserChangeForm, CustomPasswordChangeForm
from clothes.models import Cloth
from .models import Cart, PurchaseLog
from django.db.models import Count, Sum

# Create your views here.
# def temp(request):
#     context = {
#         'persons': get_user_model().objects.all()
#     }
#     return render(request, 'accounts/temp.html', context)


@login_required
def profile(request, username: str):
    User = get_user_model()
    person = User.objects.get(username=username)
    carts = Cart.objects.filter(user=person)
    purchases = PurchaseLog.objects.filter(user=person)
    purchases = PurchaseLog.objects.filter(user=person)
    
    change_form = CustomUserChangeForm()
    if request.user == person:
        change_form = CustomUserChangeForm(instance=request.user)

    context = {
        'person': person,   
        'carts': carts,
        'purchase_logs': purchases,
        'form' : change_form,
    }
    return render(request, 'accounts/profile.html', context)
    
    
def login(request):
    if request.user.is_authenticated:
        return redirect('clothes:index')
    
    if request.method == 'POST':
        login_form = CustomAuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            
            prev_url = request.session.get('prev_url')
            # 이전 페이지의 URL 정보가 있으면 해당 URL로 리다이렉트합니다.
            if prev_url:
                # 이전 페이지의 URL 정보를 삭제합니다.
                del request.session['prev_url']
                return redirect(prev_url)
            
            return redirect('clothes:index')
    else:
        login_form = CustomAuthenticationForm()
    
    request.session['prev_url'] = request.META.get('HTTP_REFERER')
    
    context = {
        'form': login_form,
    }
    return render(request, 'accounts/login.html', context)


def logout(request):
    if request.user:
        auth_logout(request)
        
        request.session['prev_url'] = request.META.get('HTTP_REFERER')
        
        prev_url = request.session.get('prev_url')
        # 이전 페이지의 URL 정보가 있으면 해당 URL로 리다이렉트합니다.
        if prev_url:
            # 이전 페이지의 URL 정보를 삭제합니다.
            del request.session['prev_url']
            return redirect(prev_url)
    
    return redirect('clothes:index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('clothes:index')
        
    if request.method == 'POST':
        register_form = CustomUserCreationForm(data=request.POST, files=request.FILES)
        if register_form.is_valid():
            user = register_form.save()
            auth_login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            
            prev_url = request.session.get('prev_url')
            # 이전 페이지의 URL 정보가 있으면 해당 URL로 리다이렉트합니다.
            if prev_url:
                # 이전 페이지의 URL 정보를 삭제합니다.
                del request.session['prev_url']
                return redirect(prev_url)
            
            return redirect('clothes:index')
    else:
        register_form = CustomUserCreationForm()
    
    request.session['prev_url'] = request.META.get('HTTP_REFERER')
    
    context = {
        'form': register_form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def delete(request, user_pk: int):
    person = get_user_model().objects.get(pk=user_pk)
    if request.user == person:
        person.delete()
        auth_logout(request)
        
    return redirect('clothes:index')


@login_required
def update(request):
    me = request.user
    if request.method == 'POST':
        print(request.FILES)
        change_form = CustomUserChangeForm(instance=me, data=request.POST, files=request.FILES)
        if change_form.is_valid():
            change_form.save()
            return redirect('accounts:profile', request.user)
    else:
        change_form = CustomUserChangeForm(instance=me)
    
    context = {
        'form': change_form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def change_password(request):
    me = request.user
    if request.method == 'POST':
        change_pwd_form = CustomPasswordChangeForm(user=me, data=request.POST)
        if change_pwd_form.is_valid():
            change_pwd_form.save()
            update_session_auth_hash(request, request.user)
            return redirect('accounts:profile', request.user)
    else:
        change_pwd_form = CustomPasswordChangeForm(user=me)
        
    context = {
        'form': change_pwd_form,
    }
    return render(request, 'accounts/change_password.html', context)


@login_required
def add_cart(request, cloth_pk: int):
    me = request.user
    cloth = Cloth.objects.get(pk=cloth_pk)
    cloth_quantity = request.POST.get('quantity')
    # cloth_size = request.POST.get('size')
    if cloth_quantity:
        Cart.objects.create(user=me, cloth=cloth, quantity=cloth_quantity)
        # Cart.objects.create(user=me, cloth=cloth, quantity=cloth_quantity, size=cloth_size)
    else:
        Cart.objects.create(user=me, cloth=cloth)
    
    return redirect('accounts:profile', request.user)


@login_required
def purchase(request, cloth_pk: int):
    me = request.user
    cloth = Cloth.objects.get(pk=cloth_pk)
    cloth_quantity = request.POST.get('quantity')
    # cloth_size = request.POST.get('size')
    if cloth_quantity:
        PurchaseLog.objects.create(user=me, cloth=cloth, quantity=cloth_quantity)
        # PurchaseLog.objects.create(user=me, cloth=cloth, quantity=cloth_quantity, size=cloth_size)
    else:
        PurchaseLog.objects.create(user=me, cloth=cloth)
    
    return redirect('accounts:profile', request.user)


@login_required
def delete_cart_item(request, username: str, cart_pk: int):
    person = get_user_model().objects.get(username=username)
    if request.user == person:
        cart = Cart.objects.get(pk=cart_pk)
        cart.delete()
        
    return redirect('accounts:profile', request.user)


@login_required
def delete_purchase_log(request, username: str, purchase_pk: int):
    person = get_user_model().objects.get(username=username)
    if request.user == person:
        purchase = PurchaseLog.objects.get(pk=purchase_pk)
        purchase.delete()
        
    return redirect('accounts:profile', request.user)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/change_password.css' %}">
{% endblock head %}

{% block content %}
<div class="password-page">
  <div class="password-page__image">
    {% if request.user.profile_image %}
    <img src="{{ request.user.profile_image.url }}" alt="Empty Profile Image" id="profileImage">
    {% else %}
    <img src="{% static 'img/common/blank_profile.jpg' %}" alt="Empty Profile Image" id="profileImage">
    {% endif %}
  </div>

  <form action="{% url 'accounts:change_password' %}" method="post" class="password-page__form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">비밀번호 변경</button>
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock head %}

{% block content %}
<div class="login-page">
    <div class="login-page__logo">
        <h1>PASSION ON</h1>
        <h4>Fashion your Passion</h4>
    </div>
    <form action="{% url 'accounts:login' %}" method="post" class="login-page__form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">로그인</button>
    </form>
    <div class="login-page__links">
        <a href="#">이메일 가입</a>
        <a href="#">이메일 찾기</a>
        <a href="#">비밀번호 찾기</a>
    </div>
    <div class="login-page__sns-login">
    {% load socialaccount %}
    <a href="{% provider_login_url 'naver' %}" class="">
        <button class="naver-login">네이버로 로그인</button>
    </a>
    
    <a href="{% provider_login_url 'kakao' %}">
        <button class="kakao-login">카카오톡으로 로그인</button>
    </a>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}


{% block head %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock head %}


{% block content %}
<div class="main-container">
    <div class="profile-page mx-auto">
        <div class="profile-page__image">
            {% if request.user.profile_image %}
            <img src="{{ request.user.profile_image.url }}" alt="Empty Profile Image" id="profileImage">
            {% else %}
            <img src="{% static 'img/common/blank_profile.jpg' %}" alt="Empty Profile Image" id="profileImage">
            {% endif %}
        </div>
        {% if request.user == person %}
        {# 본인의 프로필 페이지인 경우 - 프로필 정보 업데이트 #}
        <form action="{% url 'accounts:update' %}" method="post" enctype="multipart/form-data" class="profile-page__form">
            {% csrf_token %}
            {{ form.as_p }}
            <a href="{% url 'accounts:change_password' %}" class="container-fluid btn btn-outline-primary">패스워드 변경</a>
            <button type="submit">프로필 업데이트</button>
        </form>
        {% else %}
        {# 본인의 프로필 페이지가 아닌 경우 #}
        <div class="d-flex justify-content-evenly">
            <div class="d-flex flex-column">
                <small class="text-secondary">성</small>
                <p class="fw-bold">{{ person.last_name }}</p>
            </div>
            <div class="d-flex flex-column">
                <small class="text-secondary">이름</small>
                <p class="fw-bold">{{ person.first_name }}</p>
            </div>
        </div>
        <small class="text-secondary">이메일</small>
        <p class="fw-bold">{{ person.email }}</p>
        {% endif %}
    </div>

    <div class="right-div">

        {% if request.user == person %}
        <section class="fw-bold fs-5">장바구니</section>
        <!-- 장고 입력 예시  -->
        <div class="cart">
            {% if carts|length == 0 %}
            <p class="text-secondary text-center mt-4">장바구니가 비었습니다.</p>
            {% else %}
            <table class="table table-hover text-center text-nowrap">
                <thead class="">
                    <tr>
                        <td>상품사진</td>
                        <td>상품명</td>
                        <td>가격</td>
                        <td>개수</td>
                        <td>총 가격</td>
                        <td class="text-body-tertiary">삭제</td>
                    </tr>
                </thead>
                <tbody>
                {% for item in carts %}
                <tr>
                    <td>
                        <a href="{% url 'clothes:detail' item.cloth.pk %}" class="d-block cart-item">
                            {% if item.cloth.thumbnail %}
                            <img src="{{ item.cloth.thumbnail.url }}" alt="product_image">
                            {% else %}
                            <img src="{% static 'img/common/passionon.png' %}" alt="No Product Image" class="">
                            {% endif %}
                        </a>
                    </td>
                    <td><a href="{% url 'clothes:detail' item.cloth.pk %}" class="d-block text-nowrap overflow-hidden">{{ item.cloth.name }}</a></td>
                    <td><a href="{% url 'clothes:detail' item.cloth.pk %}" class="d-block">{{ item.cloth.price|intcomma }}원</a></td>
                    <td><a href="{% url 'clothes:detail' item.cloth.pk %}" class="d-block">{{ item.quantity }}</a></td>
                    <td><a href="{% url 'clothes:detail' item.cloth.pk %}" class="d-block">{{ item.item_cost|intcomma }}원</a></td>
                    <td>
                        <form action="{% url 'accounts:delete_cart_item' request.user item.pk %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="text-danger border-0 bg-transparent">X</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% endif %}
            {% comment %} {% for item in carts %}
            <a href="{% url 'clothes:detail' item.cloth.pk %}">
                <div class="cart-item">
                    {% if item.cloth.thumbnail %}
                    <img src="{{ item.cloth.thumbnail.url }}" alt="product_image">
                    {% else %}
                    <img src="{% static 'img/common/passionon.png' %}" alt="No Product Image" class="">
                    {% endif %}
                    <p>{{ item.cloth.name }}</p>
                    <p>{{ item.cloth.price }}원</p>
                    <p>{{ item.quantity }}개</p>
                    {# item_cost = 상품가격 * 장바구니에 담은 상품 갯수 #}
                    <p>{{ item.item_cost }}원</p>
                </div>
            </a>
            <form action="{% url 'accounts:delete_cart_item' item.pk %}" method="post">
                {% csrf_token %}
                <button type="submit" class="text-danger border-0 bg-transparent">X</button>
            </form>
            {% endfor %} {% endcomment %}
        </div>

        <section class="profile-section fw-bold fs-5">구매 내역</section>
        <div class="purchase-history">
            {% if purchase_logs|length == 0 %}
            <p class="text-secondary text-center mt-4">구매내역이 없습니다.</p>
            {% else %}
            <table class="table table-hover text-center text-nowrap">
                <thead class="">
                    <tr>
                        <td>상품사진</td>
                        <td>상품명</td>
                        <td>가격</td>
                        <td>개수</td>
                        <td>총 가격</td>
                        <td class="text-body-tertiary">삭제</td>
                    </tr>
                </thead>
                <tbody>
                {% for item in purchase_logs %}
                <tr class="">
                    <td>
                        <a href="{% url 'clothes:detail' item.cloth.pk %}" class="d-block cart-item">
                            {% if item.cloth.thumbnail %}
                            <img src="{{ item.cloth.thumbnail.url }}" alt="product_image">
                            {% else %}
                            <img src="{% static 'img/common/passionon.png' %}" alt="No Product Image" class="">
                            {% endif %}
                        </a>
                    </td>
                    <td><a href="{% url 'clothes:detail' item.cloth.pk %}" class="d-block text-nowrap overflow-hidden">{{ item.cloth.name }}</a></td>
                    <td><a href="{% url 'clothes:detail' item.cloth.pk %}" class="d-block">{{ item.cloth.price|intcomma }}원</a></td>
                    <td><a href="{% url 'clothes:detail' item.cloth.pk %}" class="d-block">{{ item.quantity }}</a></td>
                    <td><a href="{% url 'clothes:detail' item.cloth.pk %}" class="d-block">{{ item.item_cost|intcomma }}원</a></td>
                    <td>
                        <form action="{% url 'accounts:delete_purchase_log' request.user item.pk %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="text-danger border-0 bg-transparent">X</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% endif %}
            {# 이전 구매 내역 #}
            {% comment %} <div class="purchase-history">
                <div class="history-item">
                    <p>상품명</p>
                    <p>가격</p>
                    <p>개수</p>
                    <p>총 가격</p>
                </div>
                {% for item in purchase_logs %}
                <a href="{% url 'clothes:detail' item.cloth.pk %}">
                    <div class="history-item">
                        <p>{{ item.cloth.name }}</p>
                        <p>{{ item.cloth.price }}원</p>
                        <p>{{ item.quantity }}개</p>
                        {# item_cost = 상품가격 * 당시 구매한 상품 갯수 #}
                        <p>{{ item.item_cost }}원</p>
                    </div>
                </a>
                <form action="{% url 'accounts:delete_purchase_log' item.pk %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="text-danger border-0 bg-transparent">X</button>
                </form>
                {% endfor %}
            </div> {% endcomment %}
        </div>
        {% endif %}

        <section class="profile-section fw-bold fs-5 mb-3">피드</section>
        <div class="feed">
            {% if person.recommend_set.all|length == 0 %}
            <p class="text-secondary text-center mx-auto mt-5">등록한 코디가 없습니다.</p>
            {% else %}
            {% for feed in person.recommend_set.all %}
            <a href="{% url 'clothes:recommend_detail' feed.pk %}" class="">
                <div class="feed-item">
                    <div class="feed-image">
                        {% with feed.recommendimage_set.all.first.image as image %}
                        {% if image %}
                        <img src="{{ image.url }}" alt="feed_image">
                        {% else %}
                        <img src="{% static 'img/common/passionon.png' %}" alt="">
                        {% endif %}
                        {% endwith %}
                    </div>
                    <div class="feed-content">
                        <p>{{ feed.title }}</p>
                        <p>
                            {% for tag in feed.tags.all %}
                            <span class="text-secondary">#{{ tag }}</span>
                            {% endfor %}
                        </p>
                    </div>
                </div>
            </a>
            {% endfor %}
            {% endif %}
        </div>

    </div>
</div>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
{% endblock head %}


{% block content %}
<div class="signup-page">
  <div class="signup-page__logo">
    <h1>PASSION ON</h1>
    <h4>Fashion your Passion</h4>
  </div>
  <form action="{% url 'accounts:signup' %}" method="post" class="signup-page__form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">회원가입</button>
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}


{% block content %}
<main class="container">
  <h1 class="">회원정보 수정</h1>

  <form action="{% url 'accounts:update' %}" method="post" class="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <a href="{% url 'accounts:change_password' %}" class="">패스워드 변경</a>
    {% comment %} <button type="submit" class="">수정</button> {% endcomment %}
    <input type="submit" value="수정">
  </form>
</main>
{% endblock content %}