accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    # path('', views.temp, name='temp'),
    path('profile/<username>/', views.profile, name='profile'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('cart/<int:cloth_pk>/', views.add_cart, name='add_cart'),
    path('purchase/<int:cloth_pk>/', views.purchase, name='purchase'),
    
    # 아래 두 경로는 위 경로와 달리 cloth_pk가 아닌 cart_pk, purchase_pk임에 주의!!
    path('<username>/cart/<int:cart_pk>/delete/', views.delete_cart_item, name='delete_cart_item'),
    path('<username>/purchase/<int:purchase_pk>/delete/', views.delete_purchase_log, name='delete_purchase_log'),
]

clothes/urls.py
from django.urls import path
from . import views


app_name = 'clothes'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:cloth_pk>/', views.detail, name='detail'),
    path('<int:cloth_pk>/delete/', views.delete, name='delete'),
    path('<int:cloth_pk>/update/', views.update, name='update'),
    path('search/', views.search, name='search'),
    # path('tags/<int:tag_pk>/', views.tagged_clothes, name='tagged_clothes'),
    path('<int:cloth_pk>/likes/', views.likes, name='likes'),
    path('category/<str:subject>/', views.category, name='category'),
    path('recommends/create/', views.recommend_create, name='recommend_create'),
    path('recommends/<int:recommend_pk>/', views.recommend_detail, name='recommend_detail'),
    path('recommends/<int:recommend_pk>/delete/', views.recommend_delete, name='recommend_delete'),
    path('recommends/<int:recommend_pk>/update/', views.recommend_update, name='recommend_update'),
    path('recommends/<int:recommend_pk>/comments/', views.comments_create, name='comments_create'),
    path('recommends/<int:recommend_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('shop/', views.shop, name='shop'),
    path('md-pick/', views.md_pick, name='md_pick'),
    path('gender/<str:gender>/', views.gender, name='gender'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('clothes/', include('clothes.urls')),
    path('reviews/', include('reviews.urls')),
    path('accounts/', include('allauth.urls')),
    # localhost:8000을 localhost:8000/clothes로 redirect
    path('', (lambda request: redirect('clothes:index'))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <!-- css reset -->
    <link href="https://cdn.jsdelivr.net/npm/reset-css@5.0.1/reset.min.css" rel="stylesheet"> 
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- font  -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Passion+One&display=swap" rel="stylesheet">
    <!-- google icon -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- title -->
    <link rel="icon" href="{% static 'img/common/passionon-favicon.jpg' %}">
    <title>PASSION ON</title>
    {% block head %}{% endblock head %}
</head>
<body>
    
{% include 'navbar.html' %}

{% comment %} <main-content><img src="https://images.unsplash.com/photo-1527856263669-12c3a0af2aa6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80" alt=""></main-content> {% endcomment %}
{% block content %}{% endblock content %}

{% include 'footer.html' %}

<script src="{% static 'javascript/navbar.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
<!-- font awesome  -->
<script src="https://kit.fontawesome.com/a3ecfa0309.js" crossorigin="anonymous"></script>

</body>

</html>

templates/footer.html
<footer>
  <div class="footer-content row">
      <nav class = "footer-more col-md-4">
          <p>More ></p>
          <ul>
              <li><a href="#">Privacy Policy</a></li>
              <li><a href="#">Terms of Service</a></li>
          </ul>
      </nav>
      <nav class="footer-member col-md-4">
          <p>Members ></p>
          <ul>
              <li><a href="#">Chang-Jo Kim</a></li>
              <li><a href="#">Sang-Yoon Shin</a></li>
              <li><a href="#">Chung-Hyun Choi</a></li>
              <li><a href="#">Yeon-Seon Chu</a></li>
          </ul>
      </nav>
      <nav class="footer-contact col-md-4">
          <i class="fa-brands fa-instagram fa-xl"></i>
          <i class="fa-brands fa-facebook fa-xl"></i>
          <i class="fa-brands fa-twitter fa-xl"></i>
      </nav>
      <hr> 
      <p class="copyright">© 2023 Passion On. All Rights Reserved.</p>
  </div>
</footer>

templates/navbar.html
{% comment %} <div class="nav-bar2 d-flex justify-content-end align-items-center p-1">
    {% if not request.user.is_authenticated %}
    <a href="{% url 'accounts:login' %}" class="btn btn-outline-primary me-3">Login</a>
    <a href="{% url 'accounts:signup' %}" class="btn btn-outline-success">Sign-up</a>
    {% else %}
    <p class="fs-6 m-0 me-3">
        <code><a href="{% url 'accounts:profile' request.user %}">
            {{ request.user }}
        </a></code>
           <span>님, 안녕하세요!</span>
    </p>
    {% if request.user.is_superuser %}
    <a href="{% url 'clothes:create' %}" class="btn btn-warning me-3">상품 등록</a>
    {% endif %}
    <form action="{% url 'accounts:logout' %}" method="post" class="">
        {% csrf_token %}
        <button type="submit" class="btn btn-dark">Logout</button>
    </form>
    {% endif %}
</div>

<div class="nav-bar">
  <h1 class="logo"><a href="{% url 'clothes:index' %}" class="text-decoration-none">Passion On</a></h1>
  <div class="icons d-md-none">
      <div class="search-icon">
          <div class="material-symbols-outlined">search</div>
      </div>
      <div class="">
          <div class="material-symbols-outlined">notifications</div>
      </div>
      <div class="openbtn" onclick="openNav()">
          <span class="material-symbols-outlined">menu</span>
      </div>
  </div>
  <div class="gnb d-none d-md-block">
      <div class="search-and-menu">
          <form id="search-form">
              <input id="main_search" class="main_search" type="search" placeholder="Search">
              <div class="material-symbols-outlined" id="search-icon">search</div>
          </form>
          <div class="gnb-list">
              <a href="{% url 'clothes:index' %}">HOME</a>
              <a href="{% url 'clothes:shop' %}">SHOP</a>
              <a href="{% url 'accounts:profile' request.user %}">MY</a>
          </div>
      </div>
  </div>
</div>



<ul class="catemenu">
  <li class="catemenu-item">추천</li>
  <li class="catemenu-item">랭킹</li>
  <li class="catemenu-item">남성</li>
  <li class="catemenu-item">여성</li>
</ul>

<div id="mySidebar" class="sidebar">
<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
<a href="{% url 'clothes:index' %}">HOME</a>
<a href="{% url 'clothes:shop' %}">SHOP</a>
<a href="{% url 'accounts:profile' request.user %}">MY</a>
</div> {% endcomment %}

<div class="nav-bar2 d-flex justify-content-end align-items-center p-1">
    {% if not request.user.is_authenticated %}
    {% comment %} <a href="{% url 'accounts:login' %}" class="btn btn-outline-primary me-3">Login</a> {% endcomment %}
    <a href="{% url 'accounts:login' %}" class="btn btn-outline-dark btn-sm me-3">Login</a>
    {% comment %} <a href="{% url 'accounts:signup' %}" class="btn btn-outline-success">Sign-up</a> {% endcomment %}
    <a href="{% url 'accounts:signup' %}" class="btn btn-outline-dark btn-sm">Sign-up</a>
    
    
    {% else %}
    <p class="fs-6 m-0 me-3">
        <code><a href="{% url 'accounts:profile' request.user %}">
            {{ request.user }}
        </a></code>
           <span>님, 안녕하세요!</span>
    </p>
    {% if request.user.is_superuser %}
    <a href="{% url 'clothes:create' %}" class="btn btn-warning btn-sm me-2">상품 등록</a>
    {% endif %}
    <a href="{% url 'clothes:recommend_create' %}" class="btn btn-secondary btn-sm me-2">코디 등록</a>
    <form action="{% url 'accounts:logout' %}" method="post" class="">
        {% csrf_token %}
        <button type="submit" class="btn btn-dark btn-sm">Logout</button>

    </form>
    {% endif %}
</div>

<div class="nav-bar">
  <h1 class="logo"><a href="{% url 'clothes:index' %}" class="text-decoration-none">Passion On</a></h1>
  <div class="icons d-md-none">
      <div class="search-icon">
          <div class="material-symbols-outlined">search</div>
      </div>
      <div class="">
          <div class="material-symbols-outlined">notifications</div>
      </div>
      <div class="openbtn" onclick="openNav()">
          <span class="material-symbols-outlined">menu</span>
      </div>    
  </div>
  <div class="gnb d-none d-md-block">
      <div class="search-and-menu">
          <form id="search-form">
              <input id="main_search" class="main_search" type="search" placeholder="Search">
              <div class="material-symbols-outlined" id="search-icon">search</div>
          </form>
          <div class="gnb-list">
              <a href="{% url 'clothes:index' %}">HOME</a>
              <a href="{% url 'clothes:shop' %}">SHOP</a>
              <a href="{% url 'accounts:profile' request.user %}">MY</a>
          </div>
      </div>
  </div>
</div>

<ul class="catemenu">
  <li class="catemenu-item">
    <a href="{% url 'clothes:md_pick' %}">Weekly Pick</a>
  </li>
  <li class="catemenu-item">
    <a href="{% url 'clothes:gender' 'Female' %}">여성</a>
  </li>
  <li class="catemenu-item">
    <a href="{% url 'clothes:gender' 'Male' %}">남성</a>
  </li>
  <li class="catemenu-item">
    <a href="{% url 'clothes:gender' 'Unisex' %}">유니섹스</a>
  </li>
</ul>

<div id="mySidebar" class="sidebar">
<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
<a href="{% url 'clothes:index' %}">HOME</a>
<a href="{% url 'clothes:shop' %}">SHOP</a>
<a href="{% url 'accounts:profile' request.user %}">MY</a>
</div>

<script>
document.getElementById('search-form').addEventListener('submit', function(event) {
    event.preventDefault();
    const query = document.getElementById('main_search').value;
    window.location.href = "{% url 'clothes:search' %}?q=" + encodeURIComponent(query);
});
</script>